#first we print the list of students
puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# finally, we print the total number of students on one line through "print"
print "Overall, we have "
print 11
puts " great students"
#or we can split the text in between a few lines with "\n"
print "Overall, we have\n11\ngreat students"
